### ISSUE TITLE
Stop RapidConnect from issuing EPTID when no EPTID is received from the IdP.

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/rapidconnect#47]
Hi,

I've run into a weird issue.

For some reason, RapidConnect (ShibSP) received an empty set of attributes from the IdP.

However, RapidConnect rather disgracefully calculated a hash that's based on the empty string - so any user with the empty attribute set would get the same EPTID:

````
I, [2016-04-26T12:20:03.043270 #6604]  INFO -- : Established session for ()
I, [2016-04-26T12:20:03.216863 #6608]  INFO -- : Translated incoming principal  (, ) to https://rapidconnect.tuakiri.ac.nz!https://oumsa.org!jMFzRcmHQ0XmFPvyiERaUjhER3k= for aud https://oumsa.org
I, [2016-04-26T12:20:03.217533 #6608]  INFO -- : Provided details for () to service Otago University Medical Students Association(https://oumsa.org/wp-login.php)
D, [2016-04-26T12:20:03.217612 #6608] DEBUG -- : {:iss=>"https://rapidconnect.tuakiri.ac.nz", :iat=>1461630003, :jti=>"_P85b9S_NIF-IhriehSiacAMHTf1R2tW", :nbf=>1461629943, :exp=>1461630123, :typ=>"authnresponse", :aud=>"https://oumsa.org", :sub=>"https://rapidconnect.tuakiri.ac.nz!https://oumsa.org!jMFzRcmHQ0XmFPvyiERaUjhER3k=", :"https://aaf.edu.au/attributes"=>{:cn=>"", :mail=>"", :displayname=>"", :givenname=>"", :surname=>"", :edupersontargetedid=>"https://rapidconnect.tuakiri.ac.nz!https://oumsa.org!jMFzRcmHQ0XmFPvyiERaUjhER3k=", :edupersonscopedaffiliation=>"", :edupersonprincipalname=>""}}
````

I guess the correct approach would be to either not generate the value, or abort the session altogether.

What are your toughts on this?

Cheers,
Vlad

PS: We are running a very outdated version - not synced since October 2014.  However, having quickly scanned the 110 commits we are behind, it does not appear this has been fixed in the meantime...

**Comment by bradleybeddoes** [comment]
I agree this was poor but it has also been addressed as of https://github.com/ausaccessfed/rapidconnect/commit/9c68a540fddeeb806bc8ad40eb07bee68d1b220b and has been operating in our production federation since February.

We've also just added https://github.com/ausaccessfed/rapidconnect/commit/492adaf4a6103a32c20ff49d2d768441a9efc8b5 which further refines this fix (currently in the test federation, scheduled for production next Monday).

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the pointer (and sorry, should have checked the commit log more throughly).

Thanks - will aim to roll it out soon!
