### ISSUE TITLE
Created_at missing in 1.4 used with old data

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/rapidconnect#48]
Hi,

I was testing the `/export/basic` export after upgrading from 1.0 to 1.4 - and it was failing because the registration data for services created with 1.0 did not have the created_at attribute.

The exact stack trace is:

```
2016-05-16 09:29:01 - TypeError - can't convert nil into an exact number:
        /home/rapid/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/time/calculations.rb:45:in `at'
        /home/rapid/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/time/calculations.rb:45:in `at_with_coercion'
        /home/rapid/rapidconnect/rapidconnect/app/rapid_connect.rb:590:in `service_as_json'
        /home/rapid/rapidconnect/rapidconnect/app/rapid_connect.rb:579:in `block (2 levels) in <class:RapidConnect>'
        /home/rapid/rapidconnect/rapidconnect/app/rapid_connect.rb:578:in `each'
        /home/rapid/rapidconnect/rapidconnect/app/rapid_connect.rb:578:in `map'
        /home/rapid/rapidconnect/rapidconnect/app/rapid_connect.rb:578:in `block in <class:RapidConnect>'
...
```

I have been able to workaround it by:
1. Modifying the `service_as_json` function to use current time for `created_at` IFF the service has no `created_at` time recorded.
2. Modifying `/administration/services/update` to store the current time in `created_at` IFF the service has no `created_at` time recorded.

Would you welcome a PR with these two fixes?

The diff is

```
diff --git a/rapidconnect/app/rapid_connect.rb b/rapidconnect/app/rapid_connect.rb
index a4d2621..c5ed799 100644
--- a/rapidconnect/app/rapid_connect.rb
+++ b/rapidconnect/app/rapid_connect.rb
@@ -318,6 +318,7 @@ class RapidConnect < Sinatra::Base
     service.attributes = service_attrs.merge(admin_supplied_attrs)

     if service.valid?
+      service.created_at ||= Time.now.utc.to_i
       @redis.hset('serviceproviders', identifier, service.to_json)
       @app_logger.info "Service #{identifier} updated by #{session[:subject][:principal]} #{session[:subject][:cn]}"
       redirect to('/administration/services/' + identifier)
@@ -586,7 +587,7 @@ class RapidConnect < Sinatra::Base
   def service_as_json(id, service)
     { id: id,
       name: service.name,
-      created_at: Time.at(service.created_at).utc.xmlschema,
+      created_at: Time.at(service.created_at || Time.now.utc.to_i).utc.xmlschema,
       contact: {
         name: service.registrant_name,
         email: service.registrant_mail,
```

(and I can of course dice it into two separate commits)

Cheers,
Vlad

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Vlad, essentially not having `created_at` from 0.x was a mistake.

What we did was go through registration notification emails for all pre-existing instances and use those dates to populate the created_at data correctly. For anything that we couldn't find we used an approximate date (this was only 2 or 3 records).

I'm not really that keen on putting something in the code that takes us away from `created_at` being mandated.

Would this approach work in your case?

**Comment by vladimir-mencl-eresearch** [comment]
Hi Bradley,

Np - understand that.  I can do a fix at my end that would work around it.

I was expecting you might not be keen on having this in the codebase, so that's why I asked.

Btw, I bumped into this when looking into the option to use `/export/basic` for the Service Catalogue export we talked about earlier at eResearchAustraliasia last year.

I've checked and the basic export has pretty much all of the data required for the service catalogue listings there - so I might just write a small external script that messages the json from the basic export format into the format expected by the service catalogue page - I'll aim to share that once I have it.

For this, I found RapidConnect has no description field, just displayName.  Would you consider adding that in the future?

And, besides created_at, would you also consider having `updated_at` ?  (To be consistent with FR and other apps?)

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Happy for `description` and `updated_at` to be captured as future feature requests.

**Comment by vladimir-mencl-eresearch** [comment]
Submitted as #49; closing this one.
