### ISSUE TITLE
Add support for FreshDesk login

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/rapidconnect#57]
We already manage ZenDesk out of Rapid as a unique endpoint, seems fine to do the same for FreshDesk, at least for now.

Example impl: https://github.com/NeCTAR-RC/freshdesk-pip
Documentation: https://support.freshdesk.com/support/solutions/articles/31166-single-sign-on-remote-authentication-in-freshdesk

**Comment by bradleybeddoes** [comment]
Ryan: For action post monitoring development work wrap.

**Comment by bradleybeddoes** [comment]
cc @trsau

**Comment by rcaught** [comment]
@bradleybeddoes https://github.com/ausaccessfed/rapidconnect/compare/feature/freshdesk

**Comment by bradleybeddoes** [comment]
Closed by #58
